services:
  app:
    image: ghcr.io/mschwald/pvenergy:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data/models:/pvenergy/data/models
      - ./data/results:/pvenergy/data/results
    restart: unless-stopped