services:
  app:
    image: ghcr.io/mschwald/pvenergy:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data/training:/pvenergy/data/training
      - ./data/models:/pvenergy/data/models
      - ./data/results:/pvenergy/data/results
      - ./data/db:/pvenergy/data/db
    restart: unless-stopped