[build-system]
requires = ["hatchling >= 1.26", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "pvenergy"
version = "0.2.0"
authors = [
    { name = "Martin Schwald", email = "217314379+MSchwald@users.noreply.github.com" }
]
description = "ML-Pipeline & Django Dashboard for forecasting energy output of photovoltaic systems"
readme = "README.md"
requires-python = ">=3.11,<3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}
keywords = ["Photovoltaic Energy", "Machine Learning", "Django", "Solar Power", "Energy forecast"]
dynamic = ["dependencies"]

[tool.hatch.metadata]
allow-dynamic = true

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[project.urls]
Homepage = "https://github.com/MSchwald/pvenergy"

[project.scripts]
pvenergy = "main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/pvcore", "src/dashboard", "src/pvenergy", "src/main.py"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.hatch.build.targets.sdist]
include = ["src", "pyproject.toml", "README.md"]

[tool.pyright]
include = ["src"]
extraPaths = ["src"]
typeCheckingMode = "basic"
reportMissingTypeStubs = false
reportUnusedVariable = "warning"
reportUndefinedVariable = "error"
reportGeneralTypeIssues = "warning"